"""Typer CLI entrypoint for AutoBioPipe."""

from __future__ import annotations

import logging
import sys
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

from autobiopipe._version import __version__
from autobiopipe.config import load_config
from autobiopipe.detect import detect_file
from autobiopipe.pipeline import run_pipeline
from autobiopipe.report import print_saved_report

app = typer.Typer(name="autobio", add_completion=False, help="Automated QC for FASTA and FASTQ files.")
console = Console()


def _configure_logging(verbose: bool) -> None:
    """Configure root logging for the CLI.

    Args:
        verbose: Whether to enable debug logging.
    """
    logging.basicConfig(
        level=logging.DEBUG if verbose else logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    )
    logging.getLogger("matplotlib").setLevel(logging.WARNING)


@app.command("run")
def run_command(
    input_file: Path = typer.Argument(..., help="Path to the FASTA or FASTQ input file."),
    output_dir: Optional[Path] = typer.Option(
        None,
        "--output-dir",
        "-o",
        help="Directory for generated reports.",
    ),
    config: Optional[Path] = typer.Option(
        None,
        "--config",
        "-c",
        help="Path to a TOML configuration file.",
    ),
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable debug logging."),
) -> None:
    """Run the full AutoBioPipe pipeline."""
    _configure_logging(verbose)
    try:
        resolved_config = load_config(config) if config else load_config()
        if verbose:
            resolved_config.pipeline.verbose = True
        result = run_pipeline(
            input_file=input_file,
            output_dir=output_dir or resolved_config.pipeline.output_dir,
            config=resolved_config,
        )
    except Exception as exc:
        console.print(f"[red]Pipeline failed:[/red] {exc}")
        raise typer.Exit(code=1) from exc

    if result.decision.overall_status == "FAIL":
        raise typer.Exit(code=2)


@app.command("detect")
def detect_command(
    input_file: Path = typer.Argument(..., help="Path to the FASTA or FASTQ input file."),
) -> None:
    """Detect file type, compression, and pairing layout."""
    try:
        result = detect_file(input_file)
    except Exception as exc:
        console.print(f"[red]Detection failed:[/red] {exc}")
        raise typer.Exit(code=1) from exc

    console.print(result.summary())
    for warning in result.warnings:
        console.print(f"[yellow]Warning:[/yellow] {warning}")


@app.command("report")
def report_command(
    json_file: Path = typer.Argument(..., help="Path to a JSON report generated by AutoBioPipe."),
) -> None:
    """Render a saved JSON report to the terminal."""
    try:
        print_saved_report(json_file)
    except Exception as exc:
        console.print(f"[red]Report rendering failed:[/red] {exc}")
        raise typer.Exit(code=1) from exc


@app.command("version")
def version_command() -> None:
    """Print AutoBioPipe version information."""
    console.print(f"AutoBioPipe {__version__}")
    console.print(f"Python {sys.version.split()[0]}")


if __name__ == "__main__":
    app()
